name: Publicando no Dockerhub
run-name: PUBLICANDO NO DOCKERHUB
on:
    push:
        branches: [ main ]
jobs:
    test_job:
        runs-on: ubuntu - latest
        steps:
          - name: Checkout code
            uses: actions / checkout@v2
                   
          - name: Docker Login
            uses: docker/login-action@v3.2.0
            with:
                username: ${{ secrets.DOCKERHUB_USR}}
                password: ${{ secrets.DOCKERHUB_PWD}}
            
          - name: Build and push Docker images
            uses: docker/build-push-action@v6.1.0
            with:
                context: .
                tags: 'tiagothesouza/helloworld77:latest'
                push: true
      
